### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by WarranWeng** [AHupuJR/EFNet#1]
Hi,

Thanks for your great work. Any plans for releasing the dataset?
I find the link in the repo is unavailable.

Thanks a lot.

**Comment by HoseinHashemi** [comment]
Would be great to have the dataset released too.
Thanks.

**Comment by AHupuJR** [comment]
Hi, guys.
We are finding a free cloud drive to upload the dataset. And we will upload and update the link in one week.

**Comment by AHupuJR** [comment]
Hi guys, the dataset link is updated. You can download the dataset with links now.
